# Generated by Django 3.1.7 on 2021-04-07 07:22

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtail.search.index


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0003_delete_floatimage'),
        ('cpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummitWebinar',
            fields=[
                ('minilivechannel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='webinar.minilivechannel')),
                ('summit_app', models.CharField(max_length=128, verbose_name='峰会内部名')),
            ],
            options={
                'verbose_name': '峰会直播间',
                'verbose_name_plural': '峰会直播间',
            },
            bases=('webinar.minilivechannel',),
        ),
        migrations.CreateModel(
            name='SummitAgenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summit_app', models.CharField(max_length=128, verbose_name='峰会内部名')),
                ('name', models.CharField(max_length=128, verbose_name='内部名')),
                ('title', models.CharField(max_length=255, verbose_name='议程名')),
                ('sub_title', models.CharField(blank=True, max_length=255, verbose_name='副议程名')),
                ('description', wagtail.core.fields.RichTextField(blank=True, verbose_name='描述')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='开始')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='结束')),
                ('webinars', wagtail.core.fields.StreamField([('webinar', wagtail.core.blocks.StructBlock([('pre', wagtail.core.blocks.StreamBlock([('channel', wagtail.core.blocks.StructBlock([('start', wagtail.core.blocks.DateTimeBlock()), ('end', wagtail.core.blocks.DateTimeBlock(reqired=False)), ('cid', wagtail.core.blocks.CharBlock('Channel ID', max_length=255)), ('wid', wagtail.core.blocks.CharBlock('Watch ID', max_length=255, reqired=False)), ('vendor', wagtail.core.blocks.ChoiceBlock(choices=[('mudu', 'Mudu'), ('gensee', 'Geensee'), ('ext_url', 'External URL'), ('self', 'Self'), ('polyv', 'Polyv')])), ('channel_type', wagtail.core.blocks.ChoiceBlock(choices=[('live', 'Live'), ('demand', 'Demand')])), ('token', wagtail.core.blocks.CharBlock(max_length=255, reqired=False))])), ('lbreak', wagtail.core.blocks.StructBlock([('start', wagtail.core.blocks.DateTimeBlock()), ('end', wagtail.core.blocks.DateTimeBlock()), ('label', wagtail.core.blocks.CharBlock(reqired=False)), ('message', wagtail.core.blocks.CharBlock(reqired=False))], label='Live Break'))], block_counts={'channel': {'max_num': 1}, 'lbreak': {'max_num': 1}}, label='Pre Live', max_num=2, required=False)), ('live', wagtail.core.blocks.StreamBlock([('channel', wagtail.core.blocks.StructBlock([('start', wagtail.core.blocks.DateTimeBlock()), ('end', wagtail.core.blocks.DateTimeBlock(reqired=False)), ('cid', wagtail.core.blocks.CharBlock('Channel ID', max_length=255)), ('wid', wagtail.core.blocks.CharBlock('Watch ID', max_length=255, reqired=False)), ('vendor', wagtail.core.blocks.ChoiceBlock(choices=[('mudu', 'Mudu'), ('gensee', 'Geensee'), ('ext_url', 'External URL'), ('self', 'Self'), ('polyv', 'Polyv')])), ('channel_type', wagtail.core.blocks.ChoiceBlock(choices=[('live', 'Live'), ('demand', 'Demand')])), ('token', wagtail.core.blocks.CharBlock(max_length=255, reqired=False))])), ('lbreak', wagtail.core.blocks.StructBlock([('start', wagtail.core.blocks.DateTimeBlock()), ('end', wagtail.core.blocks.DateTimeBlock()), ('label', wagtail.core.blocks.CharBlock(reqired=False)), ('message', wagtail.core.blocks.CharBlock(reqired=False))], label='Live Break'))], block_counts={'channel': {'max_num': 1}, 'lbreak': {'max_num': 1}}, label='Live', max_num=2, required=False)), ('post', wagtail.core.blocks.StreamBlock([('channel', wagtail.core.blocks.StructBlock([('start', wagtail.core.blocks.DateTimeBlock()), ('end', wagtail.core.blocks.DateTimeBlock(reqired=False)), ('cid', wagtail.core.blocks.CharBlock('Channel ID', max_length=255)), ('wid', wagtail.core.blocks.CharBlock('Watch ID', max_length=255, reqired=False)), ('vendor', wagtail.core.blocks.ChoiceBlock(choices=[('mudu', 'Mudu'), ('gensee', 'Geensee'), ('ext_url', 'External URL'), ('self', 'Self'), ('polyv', 'Polyv')])), ('channel_type', wagtail.core.blocks.ChoiceBlock(choices=[('live', 'Live'), ('demand', 'Demand')])), ('token', wagtail.core.blocks.CharBlock(max_length=255, reqired=False))])), ('lbreak', wagtail.core.blocks.StructBlock([('start', wagtail.core.blocks.DateTimeBlock()), ('end', wagtail.core.blocks.DateTimeBlock()), ('label', wagtail.core.blocks.CharBlock(reqired=False)), ('message', wagtail.core.blocks.CharBlock(reqired=False))], label='Live Break'))], block_counts={'channel': {'max_num': 1}, 'lbreak': {'max_num': 1}}, label='Post Live', max_num=2, required=False))]))], blank=True, null=True, verbose_name='直播')),
            ],
            options={
                'verbose_name': '峰会议程',
                'verbose_name_plural': '峰会议程',
                'unique_together': {('summit_app', 'name')},
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('topic', models.CharField(max_length=255, verbose_name='主题')),
                ('subtopic', models.CharField(blank=True, max_length=255, verbose_name='子主题')),
                ('description', wagtail.core.fields.RichTextField(blank=True, verbose_name='描述')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='开始')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='结束')),
                ('speakers', wagtail.core.fields.StreamField([('speaker', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(label='Name', max_length=128)), ('info', wagtail.core.blocks.StreamBlock([('title', wagtail.core.blocks.CharBlock(icon='title', label='Job Title', max_length=128, required=False)), ('intro', wagtail.core.blocks.RichTextBlock(label='Introduction', required=False))], block_counts={'title': {'min_num': 0}}, label='Base Info', required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(label='Photo', required=False)), ('mobile_image', wagtail.images.blocks.ImageChooserBlock(label='Mobile Photo', required=False))]))], blank=True, null=True, verbose_name='演讲嘉宾')),
                ('agenda', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cpage.summitagenda')),
            ],
            options={
                'verbose_name': '议程项',
                'verbose_name_plural': '议程项',
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
