# Generated by Django 3.1.7 on 2021-05-19 07:14

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cpage', '0002_auto_20210407_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summitagenda',
            name='webinars',
            field=wagtail.core.fields.StreamField([('webinar', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(max_length=128, required=False)), ('lives', wagtail.core.blocks.StructBlock([('pre', wagtail.core.blocks.StreamBlock([('channel', wagtail.core.blocks.StructBlock([('start', wagtail.core.blocks.DateTimeBlock()), ('end', wagtail.core.blocks.DateTimeBlock(reqired=False)), ('cid', wagtail.core.blocks.CharBlock('Channel ID', max_length=255)), ('wid', wagtail.core.blocks.CharBlock('Watch ID', max_length=255, reqired=False)), ('vendor', wagtail.core.blocks.ChoiceBlock(choices=[('mudu', 'Mudu'), ('gensee', 'Geensee'), ('ext_url', 'External URL'), ('self', 'Self'), ('polyv', 'Polyv')])), ('channel_type', wagtail.core.blocks.ChoiceBlock(choices=[('live', 'Live'), ('demand', 'Demand')])), ('token', wagtail.core.blocks.CharBlock(max_length=255, reqired=False))])), ('lbreak', wagtail.core.blocks.StructBlock([('start', wagtail.core.blocks.DateTimeBlock()), ('end', wagtail.core.blocks.DateTimeBlock()), ('label', wagtail.core.blocks.CharBlock(reqired=False)), ('message', wagtail.core.blocks.CharBlock(reqired=False))], label='Live Break'))], block_counts={'channel': {'max_num': 1}, 'lbreak': {'max_num': 1}}, label='Pre Live', max_num=2, required=False)), ('live', wagtail.core.blocks.StreamBlock([('channel', wagtail.core.blocks.StructBlock([('start', wagtail.core.blocks.DateTimeBlock()), ('end', wagtail.core.blocks.DateTimeBlock(reqired=False)), ('cid', wagtail.core.blocks.CharBlock('Channel ID', max_length=255)), ('wid', wagtail.core.blocks.CharBlock('Watch ID', max_length=255, reqired=False)), ('vendor', wagtail.core.blocks.ChoiceBlock(choices=[('mudu', 'Mudu'), ('gensee', 'Geensee'), ('ext_url', 'External URL'), ('self', 'Self'), ('polyv', 'Polyv')])), ('channel_type', wagtail.core.blocks.ChoiceBlock(choices=[('live', 'Live'), ('demand', 'Demand')])), ('token', wagtail.core.blocks.CharBlock(max_length=255, reqired=False))])), ('lbreak', wagtail.core.blocks.StructBlock([('start', wagtail.core.blocks.DateTimeBlock()), ('end', wagtail.core.blocks.DateTimeBlock()), ('label', wagtail.core.blocks.CharBlock(reqired=False)), ('message', wagtail.core.blocks.CharBlock(reqired=False))], label='Live Break'))], block_counts={'channel': {'max_num': 1}, 'lbreak': {'max_num': 1}}, label='Live', max_num=2, required=False)), ('post', wagtail.core.blocks.StreamBlock([('channel', wagtail.core.blocks.StructBlock([('start', wagtail.core.blocks.DateTimeBlock()), ('end', wagtail.core.blocks.DateTimeBlock(reqired=False)), ('cid', wagtail.core.blocks.CharBlock('Channel ID', max_length=255)), ('wid', wagtail.core.blocks.CharBlock('Watch ID', max_length=255, reqired=False)), ('vendor', wagtail.core.blocks.ChoiceBlock(choices=[('mudu', 'Mudu'), ('gensee', 'Geensee'), ('ext_url', 'External URL'), ('self', 'Self'), ('polyv', 'Polyv')])), ('channel_type', wagtail.core.blocks.ChoiceBlock(choices=[('live', 'Live'), ('demand', 'Demand')])), ('token', wagtail.core.blocks.CharBlock(max_length=255, reqired=False))])), ('lbreak', wagtail.core.blocks.StructBlock([('start', wagtail.core.blocks.DateTimeBlock()), ('end', wagtail.core.blocks.DateTimeBlock()), ('label', wagtail.core.blocks.CharBlock(reqired=False)), ('message', wagtail.core.blocks.CharBlock(reqired=False))], label='Live Break'))], block_counts={'channel': {'max_num': 1}, 'lbreak': {'max_num': 1}}, label='Post Live', max_num=2, required=False))], required=False))], label='会议直播'))], blank=True, null=True, verbose_name='直播'),
        ),
    ]
