# Generated by Django 3.2.6 on 2021-09-02 02:31

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cpage', '0003_auto_20210519_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='floatimage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='floatimage',
            name='lives',
            field=wagtail.core.fields.StreamField([('meeting_live', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(max_length=128, required=False)), ('lives', wagtail.core.blocks.StructBlock([('pre', wagtail.core.blocks.StreamBlock([('channel', wagtail.core.blocks.StructBlock([('start', wagtail.core.blocks.DateTimeBlock()), ('end', wagtail.core.blocks.DateTimeBlock(reqired=False)), ('cid', wagtail.core.blocks.CharBlock('Channel ID', max_length=255)), ('wid', wagtail.core.blocks.CharBlock('Watch ID', max_length=255, reqired=False)), ('vendor', wagtail.core.blocks.ChoiceBlock(choices=[('mudu', 'Mudu'), ('gensee', 'Geensee'), ('ext_url', 'External URL'), ('self', 'Self'), ('polyv', 'Polyv'), ('vhall', 'Vhall')])), ('channel_type', wagtail.core.blocks.ChoiceBlock(choices=[('live', 'Live'), ('demand', 'Demand')])), ('token', wagtail.core.blocks.CharBlock(max_length=255, reqired=False))])), ('lbreak', wagtail.core.blocks.StructBlock([('start', wagtail.core.blocks.DateTimeBlock()), ('end', wagtail.core.blocks.DateTimeBlock()), ('label', wagtail.core.blocks.CharBlock(reqired=False)), ('message', wagtail.core.blocks.CharBlock(reqired=False))], label='Live Break'))], block_counts={'channel': {'max_num': 1}, 'lbreak': {'max_num': 1}}, label='Pre Live', max_num=2, required=False)), ('live', wagtail.core.blocks.StreamBlock([('channel', wagtail.core.blocks.StructBlock([('start', wagtail.core.blocks.DateTimeBlock()), ('end', wagtail.core.blocks.DateTimeBlock(reqired=False)), ('cid', wagtail.core.blocks.CharBlock('Channel ID', max_length=255)), ('wid', wagtail.core.blocks.CharBlock('Watch ID', max_length=255, reqired=False)), ('vendor', wagtail.core.blocks.ChoiceBlock(choices=[('mudu', 'Mudu'), ('gensee', 'Geensee'), ('ext_url', 'External URL'), ('self', 'Self'), ('polyv', 'Polyv'), ('vhall', 'Vhall')])), ('channel_type', wagtail.core.blocks.ChoiceBlock(choices=[('live', 'Live'), ('demand', 'Demand')])), ('token', wagtail.core.blocks.CharBlock(max_length=255, reqired=False))])), ('lbreak', wagtail.core.blocks.StructBlock([('start', wagtail.core.blocks.DateTimeBlock()), ('end', wagtail.core.blocks.DateTimeBlock()), ('label', wagtail.core.blocks.CharBlock(reqired=False)), ('message', wagtail.core.blocks.CharBlock(reqired=False))], label='Live Break'))], block_counts={'channel': {'max_num': 1}, 'lbreak': {'max_num': 1}}, label='Live', max_num=2, required=False)), ('post', wagtail.core.blocks.StreamBlock([('channel', wagtail.core.blocks.StructBlock([('start', wagtail.core.blocks.DateTimeBlock()), ('end', wagtail.core.blocks.DateTimeBlock(reqired=False)), ('cid', wagtail.core.blocks.CharBlock('Channel ID', max_length=255)), ('wid', wagtail.core.blocks.CharBlock('Watch ID', max_length=255, reqired=False)), ('vendor', wagtail.core.blocks.ChoiceBlock(choices=[('mudu', 'Mudu'), ('gensee', 'Geensee'), ('ext_url', 'External URL'), ('self', 'Self'), ('polyv', 'Polyv'), ('vhall', 'Vhall')])), ('channel_type', wagtail.core.blocks.ChoiceBlock(choices=[('live', 'Live'), ('demand', 'Demand')])), ('token', wagtail.core.blocks.CharBlock(max_length=255, reqired=False))])), ('lbreak', wagtail.core.blocks.StructBlock([('start', wagtail.core.blocks.DateTimeBlock()), ('end', wagtail.core.blocks.DateTimeBlock()), ('label', wagtail.core.blocks.CharBlock(reqired=False)), ('message', wagtail.core.blocks.CharBlock(reqired=False))], label='Live Break'))], block_counts={'channel': {'max_num': 1}, 'lbreak': {'max_num': 1}}, label='Post Live', max_num=2, required=False))], required=False))], label='Meeting Live'))], blank=True, null=True, verbose_name='Lives'),
        ),
        migrations.AlterField(
            model_name='summitagenda',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='summitagenda',
            name='webinars',
            field=wagtail.core.fields.StreamField([('webinar', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(max_length=128, required=False)), ('lives', wagtail.core.blocks.StructBlock([('pre', wagtail.core.blocks.StreamBlock([('channel', wagtail.core.blocks.StructBlock([('start', wagtail.core.blocks.DateTimeBlock()), ('end', wagtail.core.blocks.DateTimeBlock(reqired=False)), ('cid', wagtail.core.blocks.CharBlock('Channel ID', max_length=255)), ('wid', wagtail.core.blocks.CharBlock('Watch ID', max_length=255, reqired=False)), ('vendor', wagtail.core.blocks.ChoiceBlock(choices=[('mudu', 'Mudu'), ('gensee', 'Geensee'), ('ext_url', 'External URL'), ('self', 'Self'), ('polyv', 'Polyv'), ('vhall', 'Vhall')])), ('channel_type', wagtail.core.blocks.ChoiceBlock(choices=[('live', 'Live'), ('demand', 'Demand')])), ('token', wagtail.core.blocks.CharBlock(max_length=255, reqired=False))])), ('lbreak', wagtail.core.blocks.StructBlock([('start', wagtail.core.blocks.DateTimeBlock()), ('end', wagtail.core.blocks.DateTimeBlock()), ('label', wagtail.core.blocks.CharBlock(reqired=False)), ('message', wagtail.core.blocks.CharBlock(reqired=False))], label='Live Break'))], block_counts={'channel': {'max_num': 1}, 'lbreak': {'max_num': 1}}, label='Pre Live', max_num=2, required=False)), ('live', wagtail.core.blocks.StreamBlock([('channel', wagtail.core.blocks.StructBlock([('start', wagtail.core.blocks.DateTimeBlock()), ('end', wagtail.core.blocks.DateTimeBlock(reqired=False)), ('cid', wagtail.core.blocks.CharBlock('Channel ID', max_length=255)), ('wid', wagtail.core.blocks.CharBlock('Watch ID', max_length=255, reqired=False)), ('vendor', wagtail.core.blocks.ChoiceBlock(choices=[('mudu', 'Mudu'), ('gensee', 'Geensee'), ('ext_url', 'External URL'), ('self', 'Self'), ('polyv', 'Polyv'), ('vhall', 'Vhall')])), ('channel_type', wagtail.core.blocks.ChoiceBlock(choices=[('live', 'Live'), ('demand', 'Demand')])), ('token', wagtail.core.blocks.CharBlock(max_length=255, reqired=False))])), ('lbreak', wagtail.core.blocks.StructBlock([('start', wagtail.core.blocks.DateTimeBlock()), ('end', wagtail.core.blocks.DateTimeBlock()), ('label', wagtail.core.blocks.CharBlock(reqired=False)), ('message', wagtail.core.blocks.CharBlock(reqired=False))], label='Live Break'))], block_counts={'channel': {'max_num': 1}, 'lbreak': {'max_num': 1}}, label='Live', max_num=2, required=False)), ('post', wagtail.core.blocks.StreamBlock([('channel', wagtail.core.blocks.StructBlock([('start', wagtail.core.blocks.DateTimeBlock()), ('end', wagtail.core.blocks.DateTimeBlock(reqired=False)), ('cid', wagtail.core.blocks.CharBlock('Channel ID', max_length=255)), ('wid', wagtail.core.blocks.CharBlock('Watch ID', max_length=255, reqired=False)), ('vendor', wagtail.core.blocks.ChoiceBlock(choices=[('mudu', 'Mudu'), ('gensee', 'Geensee'), ('ext_url', 'External URL'), ('self', 'Self'), ('polyv', 'Polyv'), ('vhall', 'Vhall')])), ('channel_type', wagtail.core.blocks.ChoiceBlock(choices=[('live', 'Live'), ('demand', 'Demand')])), ('token', wagtail.core.blocks.CharBlock(max_length=255, reqired=False))])), ('lbreak', wagtail.core.blocks.StructBlock([('start', wagtail.core.blocks.DateTimeBlock()), ('end', wagtail.core.blocks.DateTimeBlock()), ('label', wagtail.core.blocks.CharBlock(reqired=False)), ('message', wagtail.core.blocks.CharBlock(reqired=False))], label='Live Break'))], block_counts={'channel': {'max_num': 1}, 'lbreak': {'max_num': 1}}, label='Post Live', max_num=2, required=False))], required=False))], label='会议直播'))], blank=True, null=True, verbose_name='直播'),
        ),
        migrations.AlterField(
            model_name='summitwebinar',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='summitwebinar',
            name='vendor',
            field=models.CharField(choices=[('mudu', 'Mudu'), ('gensee', 'Geensee'), ('ext_url', 'External URL'), ('self', 'Self'), ('polyv', 'Polyv'), ('vhall', 'Vhall')], max_length=128, verbose_name='Live Vendor'),
        ),
    ]
