# Generated by Django 3.1.5 on 2021-01-26 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeixinMsgLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=32)),
                ('template', models.CharField(max_length=128)),
                ('url', models.CharField(blank=True, max_length=1024, null=True)),
                ('data', models.CharField(max_length=2048)),
                ('send_result', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
