# Generated by Django 3.2.6 on 2021-09-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctools', '0002_weixinmsglog'),
    ]

    operations = [
        migrations.CreateModel(
            name='WechatMsgLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=32)),
                ('template', models.CharField(max_length=128)),
                ('url', models.CharField(blank=True, max_length=1024, null=True)),
                ('data', models.CharField(max_length=2048)),
                ('send_result', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Wechat Log',
                'verbose_name_plural': 'Wechat Logs',
            },
        ),
        migrations.DeleteModel(
            name='WeixinMsgLog',
        ),
        migrations.AlterModelOptions(
            name='smslog',
            options={'verbose_name': 'SMS Log', 'verbose_name_plural': 'SMS Logs'},
        ),
        migrations.AlterField(
            model_name='importlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
