# Generated by Django 3.2.7 on 2021-09-09 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctools', '0003_auto_20210902_0231'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.PositiveBigIntegerField(unique=True, verbose_name='号段')),
                ('province', models.CharField(max_length=64, verbose_name='省')),
                ('city', models.CharField(max_length=128, verbose_name='市')),
                ('isp', models.CharField(blank=True, max_length=64, verbose_name='运营商')),
                ('area_code', models.CharField(blank=True, max_length=64, verbose_name='区域编码')),
                ('city_code', models.CharField(blank=True, max_length=64, verbose_name='区号')),
                ('zip_code', models.CharField(blank=True, max_length=64, verbose_name='邮政编码')),
                ('types', models.CharField(blank=True, max_length=64, verbose_name='类型')),
            ],
            options={
                'verbose_name': 'Mobile Location',
                'verbose_name_plural': 'Mobile Locations',
            },
        ),
    ]
