# Generated by Django 3.1.4 on 2021-01-15 06:20

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.search.index


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloatImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='Float Code')),
                ('url', models.URLField(blank=True, verbose_name='Float URL')),
                ('lives', wagtail.core.fields.StreamField([('meeting_live', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(max_length=128, required=False)), ('lives', wagtail.core.blocks.StructBlock([('pre', wagtail.core.blocks.StreamBlock([('channel', wagtail.core.blocks.StructBlock([('start', wagtail.core.blocks.DateTimeBlock()), ('end', wagtail.core.blocks.DateTimeBlock(reqired=False)), ('cid', wagtail.core.blocks.CharBlock('Channel ID', max_length=255)), ('wid', wagtail.core.blocks.CharBlock('Watch ID', max_length=255, reqired=False)), ('vendor', wagtail.core.blocks.ChoiceBlock(choices=[('mudu', 'Mudu'), ('gensee', 'Geensee'), ('ext_url', 'External URL'), ('self', 'Self'), ('polyv', 'Polyv')])), ('channel_type', wagtail.core.blocks.ChoiceBlock(choices=[('live', 'Live'), ('demand', 'Demand')])), ('token', wagtail.core.blocks.CharBlock(max_length=255, reqired=False))])), ('lbreak', wagtail.core.blocks.StructBlock([('start', wagtail.core.blocks.DateTimeBlock()), ('end', wagtail.core.blocks.DateTimeBlock()), ('label', wagtail.core.blocks.CharBlock(reqired=False)), ('message', wagtail.core.blocks.CharBlock(reqired=False))], label='Live Break'))], block_counts={'channel': {'max_num': 1}, 'lbreak': {'max_num': 1}}, label='Pre Live', max_num=2, required=False)), ('live', wagtail.core.blocks.StreamBlock([('channel', wagtail.core.blocks.StructBlock([('start', wagtail.core.blocks.DateTimeBlock()), ('end', wagtail.core.blocks.DateTimeBlock(reqired=False)), ('cid', wagtail.core.blocks.CharBlock('Channel ID', max_length=255)), ('wid', wagtail.core.blocks.CharBlock('Watch ID', max_length=255, reqired=False)), ('vendor', wagtail.core.blocks.ChoiceBlock(choices=[('mudu', 'Mudu'), ('gensee', 'Geensee'), ('ext_url', 'External URL'), ('self', 'Self'), ('polyv', 'Polyv')])), ('channel_type', wagtail.core.blocks.ChoiceBlock(choices=[('live', 'Live'), ('demand', 'Demand')])), ('token', wagtail.core.blocks.CharBlock(max_length=255, reqired=False))])), ('lbreak', wagtail.core.blocks.StructBlock([('start', wagtail.core.blocks.DateTimeBlock()), ('end', wagtail.core.blocks.DateTimeBlock()), ('label', wagtail.core.blocks.CharBlock(reqired=False)), ('message', wagtail.core.blocks.CharBlock(reqired=False))], label='Live Break'))], block_counts={'channel': {'max_num': 1}, 'lbreak': {'max_num': 1}}, label='Live', max_num=2, required=False)), ('post', wagtail.core.blocks.StreamBlock([('channel', wagtail.core.blocks.StructBlock([('start', wagtail.core.blocks.DateTimeBlock()), ('end', wagtail.core.blocks.DateTimeBlock(reqired=False)), ('cid', wagtail.core.blocks.CharBlock('Channel ID', max_length=255)), ('wid', wagtail.core.blocks.CharBlock('Watch ID', max_length=255, reqired=False)), ('vendor', wagtail.core.blocks.ChoiceBlock(choices=[('mudu', 'Mudu'), ('gensee', 'Geensee'), ('ext_url', 'External URL'), ('self', 'Self'), ('polyv', 'Polyv')])), ('channel_type', wagtail.core.blocks.ChoiceBlock(choices=[('live', 'Live'), ('demand', 'Demand')])), ('token', wagtail.core.blocks.CharBlock(max_length=255, reqired=False))])), ('lbreak', wagtail.core.blocks.StructBlock([('start', wagtail.core.blocks.DateTimeBlock()), ('end', wagtail.core.blocks.DateTimeBlock()), ('label', wagtail.core.blocks.CharBlock(reqired=False)), ('message', wagtail.core.blocks.CharBlock(reqired=False))], label='Live Break'))], block_counts={'channel': {'max_num': 1}, 'lbreak': {'max_num': 1}}, label='Post Live', max_num=2, required=False))], required=False))], label='Meeting Live'))], blank=True, null=True, verbose_name='Lives')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image')),
                ('image_mobile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Mobile Image')),
            ],
            options={
                'verbose_name': 'Float Image',
                'verbose_name_plural': 'Float Images',
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
