# Generated by Django 3.1.5 on 2021-01-19 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniLiveChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(choices=[('mudu', 'Mudu'), ('gensee', 'Geensee'), ('ext_url', 'External URL'), ('self', 'Self'), ('polyv', 'Polyv')], max_length=128, verbose_name='Live Vendor')),
                ('channel_type', models.CharField(choices=[('live', 'Live'), ('demand', 'Demand')], max_length=16, verbose_name='Channel Type')),
                ('cid', models.CharField(db_index=True, max_length=255, verbose_name='Channel ID')),
                ('wid', models.CharField(blank=True, db_index=True, max_length=512, verbose_name='Watch ID')),
                ('token', models.CharField(blank=True, max_length=128, verbose_name='Token')),
            ],
            options={
                'verbose_name': 'Mini Live Channel',
                'verbose_name_plural': 'Mini Live Channels',
            },
        ),
    ]
