# Generated by Django 3.1.5 on 2021-01-21 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0002_minilivechannel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FloatImage',
        ),
    ]
