# Generated by Django 3.2.6 on 2021-09-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0003_delete_floatimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minilivechannel',
            name='vendor',
            field=models.CharField(choices=[('mudu', 'Mudu'), ('gensee', 'Geensee'), ('ext_url', 'External URL'), ('self', 'Self'), ('polyv', 'Polyv'), ('vhall', 'Vhall')], max_length=128, verbose_name='Live Vendor'),
        ),
    ]
